spring: 
  profiles: 
     active:
     -dev
---
spring: 
  profiles: dev  #开发环境
  application: 
      name: mscloud-config-lee-dev
---
spring: 
  profiles: test  #测试环境
  application: 
      name: mscloud-config-lee-test
#保存为UTF-8格式